version: '2'
services:
  db:
    container_name: db
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jhipster
    ports:
      - '3308:3306'
  myapp-app:
    image: myapp
    depends_on:
      - db
    build:
      context: ../
      dockerfile: src/Myapp/Dockerfile
    ports:
      - 80:80
